name: cui-http
description: CUI HTTP client utilities

release:
  current-version: 1.3.6
  next-version: 1.4-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21","25"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-snapshot: 'release-snapshot,javadoc'
  maven-profiles-release: 'release,javadoc'
  npm-cache: false

sonar:
  project-key: cuioss_cui-http
  enabled: true
  skip-on-dependabot: true

pages:
  reference: cui-http
  deploy-at-release: true

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300
