/*
 * Copyright © 2025-present CUI-OpenSource-Software (info@cuioss.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.http.security.tests;

import de.cuioss.http.security.config.SecurityConfiguration;
import de.cuioss.http.security.core.UrlSecurityFailureType;
import de.cuioss.http.security.exceptions.UrlSecurityException;
import de.cuioss.http.security.generators.injection.ProtocolHandlerAttackGenerator;
import de.cuioss.http.security.monitoring.SecurityEventCounter;
import de.cuioss.http.security.pipeline.URLPathValidationPipeline;
import de.cuioss.test.generator.junit.EnableGeneratorController;
import de.cuioss.test.generator.junit.parameterized.TypeGeneratorSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/**
 * T24: Test protocol handler attacks
 *
 * <p>
 * A protocol handler attack hands the application a value that starts with a scheme a URL
 * parser executes or dereferences - {@code javascript:}, {@code vbscript:}, {@code data:} or
 * {@code file:}. The pattern stage matches those schemes at the start of the value, raw and
 * again after decoding, and rejects the value as
 * {@link UrlSecurityFailureType#SUSPICIOUS_PATTERN_DETECTED} when
 * {@code failOnSuspiciousPatterns} is enabled.
 * </p>
 *
 * <h3>Configuration and payload shape</h3>
 * <p>
 * The pipeline under test uses {@link SecurityConfiguration#strict()}, which enables the scheme
 * match and seeds no path block-list - so {@code SUSPICIOUS_PATTERN_DETECTED} can only come from
 * the scheme. Every payload carries a scheme and an otherwise legal path: no traversal sequence
 * and no character outside the path character set, either of which would be rejected by another
 * mechanism before the scheme is looked at.
 * </p>
 *
 * <h3>Security Standards</h3>
 * <ul>
 *   <li>RFC 3986: Uniform Resource Identifier (URI): Generic Syntax</li>
 *   <li>OWASP URL Validation Guidelines</li>
 *   <li>W3C URL Standard</li>
 *   <li>CVE-2019-11023, CVE-2020-6519, CVE-2021-30547</li>
 * </ul>
 *
 * Implements: Task T24 from HTTP verification specification
 *
 * @author Claude Code Generator
 * @since 1.0
 */
@EnableGeneratorController
@DisplayName("T24: Protocol Handler Attack Tests")
class ProtocolHandlerAttackTest {

    private URLPathValidationPipeline pipeline;
    private SecurityEventCounter eventCounter;

    @BeforeEach
    void setUp() {
        eventCounter = new SecurityEventCounter();
        pipeline = new URLPathValidationPipeline(SecurityConfiguration.strict(), eventCounter);
    }

    /**
     * Test all protocol handler attack patterns generated by ProtocolHandlerAttackGenerator.
     *
     * @param protocolAttackPattern A malicious protocol handler pattern
     */
    @ParameterizedTest
    @TypeGeneratorSource(value = ProtocolHandlerAttackGenerator.class, count = 64)
    @DisplayName("Every generated protocol handler attack is rejected for its scheme")
    void shouldRejectAllProtocolHandlerAttackPatterns(String protocolAttackPattern) {
        assertEquals(PathWireForm.WIRE_CLEAN, PathWireForm.of(protocolAttackPattern),
                () -> "The scheme must be the only rejectable property: " + protocolAttackPattern);
        assertFalse(PathWireForm.carriesListedTraversalSpelling(protocolAttackPattern),
                () -> "The scheme must be the only rejectable property: " + protocolAttackPattern);

        var exception = assertRejected(protocolAttackPattern);

        assertEquals(UrlSecurityFailureType.SUSPICIOUS_PATTERN_DETECTED, exception.getFailureType(),
                () -> "Unexpected verdict for: " + protocolAttackPattern);
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "javascript:alert('XSS')",
            "javascript:eval(String.fromCharCode(97,108,101,114,116,40,39,88,83,83,39,41))/admin",
            "javascript:window.location='http://evil.com'",
            "javascript:document.location.href='malicious.com'",
            "javascript:fetch('/etc/passwd').then(console.log)",
            "javascript:/*comment*/alert('XSS')",
            "javascript://javascript:alert('XSS')",
            "vbscript:msgbox('XSS')"
    })
    @DisplayName("Script protocol attacks are rejected as SUSPICIOUS_PATTERN_DETECTED")
    void shouldBlockScriptProtocolAttacks(String pattern) {
        var exception = assertRejected(pattern);

        assertEquals(UrlSecurityFailureType.SUSPICIOUS_PATTERN_DETECTED, exception.getFailureType(),
                () -> "Unexpected verdict for: " + pattern);
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "data:text/html,%3Cscript%3Ealert('XSS')%3C/script%3E",
            "data:application/javascript,alert('XSS')/admin/config",
            "data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4=",
            "data:image/svg+xml,%3Csvg%3E%3Cscript%3Ealert('XSS')%3C/script%3E%3C/svg%3E",
            "data:text/plain,etc/passwd",
            "data:,admin/config"
    })
    @DisplayName("Data URI exploitation patterns are rejected as SUSPICIOUS_PATTERN_DETECTED")
    void shouldBlockDataURIExploitationPatterns(String pattern) {
        var exception = assertRejected(pattern);

        assertEquals(UrlSecurityFailureType.SUSPICIOUS_PATTERN_DETECTED, exception.getFailureType(),
                () -> "Unexpected verdict for: " + pattern);
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "file:///etc/passwd",
            "file:////etc/passwd",
            "file://localhost/etc/passwd",
            "file:///c:/windows/win.ini",
            "file://admin:password@evil.com/etc/shadow"
    })
    @DisplayName("File protocol exploitation patterns are rejected as SUSPICIOUS_PATTERN_DETECTED")
    void shouldBlockFileProtocolExploitationPatterns(String pattern) {
        var exception = assertRejected(pattern);

        assertEquals(UrlSecurityFailureType.SUSPICIOUS_PATTERN_DETECTED, exception.getFailureType(),
                () -> "Unexpected verdict for: " + pattern);
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "JAVASCRIPT:alert('XSS')/admin",
            "JavaScript:alert('XSS')",
            "jAvAsCrIpT:alert(1)",
            "DATA:text/html,alert(1)",
            "FILE:///etc/passwd",
            "VBScript:msgbox(1)"
    })
    @DisplayName("A scheme in another letter case is rejected as SUSPICIOUS_PATTERN_DETECTED")
    void shouldBlockProtocolCaseManipulation(String pattern) {
        var exception = assertRejected(pattern);

        assertEquals(UrlSecurityFailureType.SUSPICIOUS_PATTERN_DETECTED, exception.getFailureType(),
                () -> "Unexpected verdict for: " + pattern);
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "%6a%61%76%61%73%63%72%69%70%74:alert('XSS')/admin",
            "j%61vascript:alert(1)",
            "javascript%3Aalert(1)",
            "%64%61%74%61:text/html,alert(1)",
            "%66%69%6c%65:///etc/passwd"
    })
    @DisplayName("A percent-encoded scheme is rejected as SUSPICIOUS_PATTERN_DETECTED after decoding")
    void shouldBlockProtocolEncodingAttacks(String pattern) {
        var exception = assertRejected(pattern);

        assertEquals(UrlSecurityFailureType.SUSPICIOUS_PATTERN_DETECTED, exception.getFailureType(),
                () -> "Unexpected verdict for: " + pattern);
    }

    /**
     * The scheme match is anchored to the start of the value. A scheme-like token in a later
     * path segment is ordinary REST vocabulary and is not a protocol handler.
     *
     * @param path a legitimate path carrying a scheme-like token after its first segment
     */
    @ParameterizedTest
    @ValueSource(strings = {"/v1/data:export", "/api/file:metadata", "/docs/javascript:basics"})
    @DisplayName("A scheme-like token in a later path segment is accepted unchanged")
    void shouldAcceptSchemeLikeTokenInLaterSegment(String path) {
        Optional<String> validated = assertDoesNotThrow(() -> pipeline.validate(path),
                () -> "A scheme-like token after the first segment is not a protocol handler: " + path);

        assertEquals(Optional.of(path), validated, "A legitimate path is returned unchanged");
        assertEquals(0, eventCounter.getTotalCount(), "An accepted path records no security event");
    }

    /**
     * Asserts the rejection itself, the preserved input and the single recorded event; the
     * failure type is asserted by the caller.
     */
    private UrlSecurityException assertRejected(String pattern) {
        var exception = assertThrows(UrlSecurityException.class, () -> pipeline.validate(pattern),
                () -> "Protocol handler attack should be rejected: " + pattern);
        assertEquals(pattern, exception.getOriginalInput(), "Original input should be preserved in exception");
        assertEquals(1, eventCounter.getTotalCount(), "Exactly one security event should be recorded");
        return exception;
    }
}
